"""
Poll-Rover Weekly KPI Aggregator
Aggregates structured logs from agents to generate a weekly performance report.
"""

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from collections import defaultdict

IST = timezone(offset=timedelta(hours=5, minutes=30))

def aggregate_kpis(log_dir: Path, days_back: int = 7):
    """Scan log files and aggregate KPIs for the last X days."""
    cutoff = datetime.now(IST) - timedelta(days=days_back)
    stats = defaultdict(lambda: defaultdict(list))
    
    if not log_dir.exists():
        print(f"Log directory {log_dir} not found.")
        return stats

    for log_file in log_dir.glob("*.jsonl"):
        agent_name = log_file.stem
        with open(log_file, "r", encoding="utf-8") as f:
            for line in f:
                try:
                    entry = json.loads(line)
                    ts = datetime.fromisoformat(entry["timestamp"])
                    
                    if ts < cutoff:
                        continue
                        
                    if "kpi_name" in entry:
                        # Use agent_target from metadata if this is a cross-agent metric
                        target_agent = agent_name
                        if "data" in entry and isinstance(entry["data"], dict):
                            target_agent = entry["data"].get("agent_target", agent_name)
                            
                        stats[target_agent][entry["kpi_name"]].append({
                            "value": entry["kpi_value"],
                            "unit": entry["kpi_unit"]
                        })
                except (json.JSONDecodeError, KeyError, ValueError):
                    continue
                    
    return stats

def generate_report(stats, output_path: Path):
    """Generate a markdown report from aggregated stats."""
    report_lines = [
        "# 📊 Weekly Agent Performance Report",
        f"**Generated at:** {datetime.now(IST).strftime('%Y-%m-%d %H:%M:%S')} IST",
        "\n## Overview\n",
        "| Agent | KPI | Average Value | Unit | Samples |",
        "| :--- | :--- | :--- | :--- | :--- |"
    ]
    
    for agent, kpis in sorted(stats.items()):
        for kpi_name, values in sorted(kpis.items()):
            avg_val = sum(v["value"] for v in values) / len(values)
            unit = values[0]["unit"]
            count = len(values)
            report_lines.append(f"| {agent} | {kpi_name} | {avg_val:.2f} | {unit} | {count} |")
            
    if not stats:
        report_lines.append("| N/A | No metrics found in last 7 days | - | - | 0 |")
        
    report_lines.append("\n---\n*Automated report generated by Poll-Rover SRE Ops.*")
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))
    
    print(f"Report generated: {output_path}")

if __name__ == "__main__":
    project_root = Path(__file__).parent.parent
    logs = project_root / "ops_logs"
    report = project_root / "reports" / "weekly_perf.md"
    
    kpi_stats = aggregate_kpis(logs)
    generate_report(kpi_stats, report)
